ALTER TABLE players ALTER COLUMN position TYPE VARCHAR(10);
DROP TYPE IF EXISTS player_position CASCADE;

ALTER TABLE invites ALTER COLUMN status DROP DEFAULT;
ALTER TABLE invites ALTER COLUMN status TYPE VARCHAR(20);
DROP TYPE IF EXISTS invite_status CASCADE;
